let initialized = false

export function initSpreadJSLicense(): void {
  if (initialized) return
  if (typeof window.GC === 'undefined') return

  const sheetsKey = 'sjs.ben-china.org.cn,E329943193644278#B1XM3QXR4YzUsBnaMxWRyg4KDR5UkFUW73kS9UGcyZXRZZHZx2UURNkVxglZxdWNTdGeopEWSBTR0NEW0h6NwREWF5GZoZFdHp5ZoVlYEd6LpJHZkRWbvNzMWdFbNR6YGJ5Kn9Uahl4axJHUzYHan9UWrcmRRpEMzZTaTZHUulmWWZWa7l4ZFFHZ7s6YstUYqB7d6lzLKBjWnV5KIh5ZBBlWIJWW4R7RZNEbxZGcjN4NjxkRoh6c4cUeFhkY4kUUtp5akZET7NHMZVVUSV4UBJ7S7QzLuplZatCUT9kT8ZWUS9GRSdEdxg4VB5USpB5by9UThBVUkJGZ7hke5RHMLRWYip4bvYHeT3UOxYHUztSQiojITJCLiUDOCBzMFFUMiojIIJCL8QDOxYTO6QjN0IicfJye#4Xfd5nIIlkSCJiOiMkIsICOx8idgMlSgQWYlJHcTJiOi8kI1tlOiQmcQJCLiETN6ATNwASNwQDM6IDMyIiOiQncDJCLigTM4AjNyAjMiojIwhXRiwiIuNmLnJ7buEmbph6Yt8WZi9ycqNnI0IyctRkIsICuPWOrFWOkZmeica+rcaOgKaekneOsVa+sieevDiukBaen4i+t5aui8SuI0ISYONkIsUWdyRnOiwmdFJCLigzNyQDN6MTOxMDN9kjMzIiOiQWSiwSfdtlOicGbmJCLlNHbhZmOiI7ckJye0ICbuFkI1pjIEJCLi4TP7R4aoFHNx8kTGRzKKpkSpZTSpZ5aLlEW4dEdBRzaXVXNKh6QxBDWxknN6FFWyRnSs3UZFJWa4I6VFNlRupWM6kTQptmdcp'

  const designerKey = 'sjs.ben-china.org.cn,E234972387644114#B1tQ5REJ5cLFzRrMEawA7U9BXWK3mSBJGMn3GSFdneid5d7l5LxMUaxZGSB9EV9oUOSpEMMVne9pnZ6glcwp4NDlkSyoXduN4di9WMwImUWV4SphVUNF6RoZVeUJ5MxtiN53kZP9mZpVUZyR7NCVVRTFVWaNFbtlnQMpERHBHTvRXcSdXWPRGdwoXUycTVvVWQRtyTyQ7dQp5c8hndOxUOptSahBDO5FHahpmbEJVWIpkYyk4UUNVZil5aQpVdKZ4YUxUMRVlastGNZRVNWJ5dZZGZzpXRQdES8tSZKpmRRlEbmREMudjZvNGUH36M5RjWPhmW5ZEdBNXViFHOkdFeIdzSOp4KzYWSiojITJCLikTQGFDRFNkNiojIIJCL7ATM4ETO4EzN0IicfJye#4Xfd5nI9k5MzIiOiMkIsICOx8idg86bkRWQtIXZudWazVGRtMlSkFWZyB7UiojIOJyebpjIkJHUiwiIyUjNwUDMgUDM4AjNyAjMiojI4J7QiwiI8EDNwYjMwIjI0ICc8VkIsIibj9yZy3mLh9WaoNWLuVmYuMnazJiOiMXbEJCLig1jlzahlDZmpnInm/KnmDoimH9pnDblmPron71goLZgm7JtofbtmrIukLiOiEmTDJCLlVnc4pjIsZXRiwiI4ETM4QjN7gzMycTO4MjMiojIklkI1pjIEJCLi4TPRRVULJ7UlJFbPJHey2CZHdlRiJWUupESHZWVRZnSiNTe8RmQvoFORhXU4pGSlJzZW5mbw2UWoFVQYlFbz34aEJkWxdDazMzZjNVSMhib'

  if (window.GC.Spread?.Sheets) {
    window.GC.Spread.Sheets.LicenseKey = sheetsKey
  }
  if (designerKey && window.GC.Spread?.Sheets?.Designer) {
    window.GC.Spread.Sheets.Designer.LicenseKey = designerKey
  }

  initialized = true
}
