-- ============================================================
-- Migration 26: Remove legacy report data + activate template
-- Part of: Complete removal of legacy report generation code
-- ============================================================

-- 1. Soft-delete all legacy reports (reportType=1)
-- These were generated by the now-removed WordReportBuilder
-- and have reportHtml=NULL (causing "报告内容为空" in the editor)
UPDATE ar_report
SET deleted = 1,
    update_by = 'SYSTEM_MIGRATION',
    update_time = NOW()
WHERE report_type = 1
  AND deleted = 0;

-- 2. Activate the report template (ensure template-based generation works)
-- Only activate if there's at least one template
UPDATE ar_report_template
SET is_active = 1,
    update_by = 'SYSTEM_MIGRATION',
    update_time = NOW()
WHERE id = (
    SELECT id FROM (
        SELECT id FROM ar_report_template
        WHERE deleted = 0
        ORDER BY create_time DESC
        LIMIT 1
    ) AS t
)
AND (is_active IS NULL OR is_active = 0);
